spring:
  datasource:
    url: jdbc:postgresql://ec2-54-208-104-27.compute-1.amazonaws.com:5432/d56nf8oooj2da3
    username: sktsyuwdiilsvt
    password: a3f2a7da77099d48b59b885cb709f757d8840543023b002a07b647941d25cec8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

twilio:
  account_sid: AC226790d7794304cda60486beda30130e
  auth_token: 03cadf483f451c2166808a0b08b9ff72
  trial_number: +16307934582

allowed:
  origin: http://localhost:3000

server:
  error:
    include-message: always
