spring:
  spring:
    datasource:
      hikari:
        minimumIdle: 2
        maximumPoolSize: 10
        idleTimeout: 120000
        connectionTimeout: 300000
        leakDetectionThreshold: 300000
  datasource:
    driver-Class-Name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true